from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd
import streamlit as st
import altair as alt


st.set_page_config(page_title="City Rides Lakehouse", layout="wide")

DATA_PATH = Path("data/warehouse.duckdb")

st.title("City Rides Lakehouse Dashboard")
st.caption("Explore hourly trip metrics generated by the pipeline.")

if not DATA_PATH.exists():
    st.warning("Warehouse not found. Run the pipeline first to generate data.")
    st.stop()

@st.cache_data(ttl=300)
def load_hourly_metrics() -> pd.DataFrame:
    con = duckdb.connect(str(DATA_PATH), read_only=True)
    try:
        df = con.execute(
            """
            SELECT
              pickup_date,
              pickup_hour,
              zone_id,
              trip_count,
              avg_trip_distance,
              avg_fare_amount,
              total_revenue
            FROM fct_trip_hourly
            ORDER BY pickup_date, pickup_hour
            """
        ).df()
    finally:
        con.close()

    df["pickup_date"] = pd.to_datetime(df["pickup_date"])
    return df


df = load_hourly_metrics()

col1, col2, col3 = st.columns(3)
col1.metric("Total Trips", f"{df['trip_count'].sum():,}")
col2.metric("Total Revenue", f"${df['total_revenue'].sum():,.2f}")
col3.metric("Avg Fare", f"${df['avg_fare_amount'].mean():.2f}")

st.subheader("Trips Over Time")
chart = (
    alt.Chart(df)
    .mark_line()
    .encode(
        x=alt.X("pickup_date:T", title="Pickup Date"),
        y=alt.Y("trip_count:Q", title="Trips"),
        color=alt.Color("zone_id:N", legend=None),
        tooltip=["pickup_date:T", "pickup_hour:Q", "zone_id:N", "trip_count:Q"],
    )
)

st.altair_chart(chart, use_container_width=True)

st.subheader("Sample Data")
st.dataframe(df.head(50), use_container_width=True)
